version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/dev-requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Build
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements/dev-requirements.txt

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "requirements/dev-requirements.txt" }}

      - run:
          name: Static tests
          command:  |
            . .venv/bin/activate
            black src/ tests/
            mypy src/ tests/
            pylint src/ tests/
            flake8 src/ tests/

      - run:
          name: Unit tests
          command: |
            . .venv/bin/activate
            pytest --cov

      - store_artifacts:
          path: .converage
          destination: test-reports
