version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "poetry.lock" }}
            - dependencies-

      - run:
          name: Build
          command: |
            poetry install

      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
          key: dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: Static tests
          command:  |
            poetry run black src/ tests/
            poetry run mypy src/ tests/
            poetry run pylint src/ tests/
            poetry run flake8 src/ tests/

      - run:
          name: Unit tests
          command: |
            poetry run pytest --cov

      - store_artifacts:
          path: .converage
          destination: test-reports
